# Generated by Django 4.0.3 on 2022-03-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.png', upload_to='profile_images')),
                ('course', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
