# Generated by Django 4.0.3 on 2022-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.CharField(choices=[('Desenvolvimento de Sistemas', 'Desenvolvimento de Sistemas'), ('Logistica', 'Logistica')], default='Logistica', max_length=30),
        ),
    ]
