# Generated by Django 4.0.3 on 2022-06-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='modality',
            field=models.CharField(choices=[('Subsequente', 'Subsequente'), ('Integrado', 'Integrado')], default='Integrado', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Cursando', 'Cursando'), ('Finalizado', 'Finalizado')], default='Cursando', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resumes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.CharField(choices=[('Desenvolvimento de Sistemas', 'Desenvolvimento de Sistemas'), ('Logistica', 'Logistica')], default='Logistica', max_length=50),
        ),
    ]
