# Generated by Django 4.0.3 on 2022-06-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_modality_resume_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_skills', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('basics_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
