# Generated by Django 4.0.3 on 2022-06-13 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledge',
            name='resumes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
