# Generated by Django 4.0.3 on 2022-06-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_knowledge_created_at_knowledge_resumes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='languages',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='english',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Intermediario', 'Intermediário'), ('Avançado', 'Avançado')], default='Basico', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='spanish',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Intermediario', 'Intermediário'), ('Avançado', 'Avançado')], default='Basico', max_length=50),
        ),
    ]
