# Generated by Django 4.0.3 on 2022-06-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_knowledge_english_alter_knowledge_spanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='english',
            field=models.CharField(choices=[('Nenhum', 'Nenhum'), ('Basico', 'Basico'), ('Intermediario', 'Intermediário'), ('Avançado', 'Avançado')], default='Nenhum', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='spanish',
            field=models.CharField(choices=[('Nenhum', 'Nenhum'), ('Basico', 'Basico'), ('Intermediario', 'Intermediário'), ('Avançado', 'Avançado')], default='Nenhum', max_length=50),
        ),
    ]
