# Generated by Django 4.0.3 on 2022-06-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_knowledge_english_alter_knowledge_spanish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='resumes',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='knowledge',
            old_name='resumes',
            new_name='resume',
        ),
    ]
