# Generated by Django 4.0.3 on 2022-06-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_rename_resumes_experience_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='resume',
            new_name='resume_experience',
        ),
        migrations.RenameField(
            model_name='knowledge',
            old_name='resume',
            new_name='resume_knowledge',
        ),
    ]
